services:
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: cases123
      MYSQL_ROOT_PASSWORD: cases123
      MYSQL_USER: root
      MYSQL_DATABASE: case_studies
    ports:
      - "3306:3306"

  web:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database